### ISSUE TITLE
Add sidebar navigation to styleguide page

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/honeycrisp-gem#112]
Let's add a navigation sidebar to the resource page!

![sidebar](https://user-images.githubusercontent.com/2693690/60376291-b6bc2700-99c2-11e9-8e56-8bdeb184d078.png)
---
![image](https://user-images.githubusercontent.com/2693690/71933159-50287a80-3156-11ea-835a-3c5c455cb234.png)

**Sidebar behavior and style**
- Bar has a fixed, with 100% height
- Bar is scrollable within
- The links can be anchor links, or links to external pages
- The `active` link updates as the user scrolls
- 2px black right border. This looks a little goofy, but we'll be updating the resource page with the new styles and it'll look better.
- Grids are hard, so in the mock I just stuck the sidebar onto the side. Let's play around with different widths 
- On mobile/tablet, use a `Menu` button with a dropdown

**Type**
-  Section headers have `h2` styling and are `color--grey-dark` with a `color--green-light` background
- Subitems are body text
- Active items are bold with a 2px `color--teal` left border
- Hover state is underlined 
- We can play around with the spacing to see what feels rights, but the mockup has a line height of 16px, with 29px for the last item of a section. 
![image](https://user-images.githubusercontent.com/2693690/60371172-4fe04300-99ad-11e9-9897-1244ae9f6c94.png)

**Content**
- This will change in the (near?) future, mock up reflects that
- For implementation, start with:
```
- For Engineers
 - Form Builder
 - Emojis
- Atoms
 - [sub-items]
- Molecules
 - [sub-items]
- Organisms
 - [sub-items]
```
- Remove nav links from the header

**Comment by SymonneSingleton** [comment]
Current Bugs/ Unfinished Functionality
Outstanding Issues to be addressed:
- selection states are off. 
1. View Menu on right in full screen. All elements look active/ bold
2. Select an element. That element stays active/bold. All others are unbolded

- In the smaller responsive view, toggling for the Menu/Close button is off.
Replicate:
1. Select Menu in a smaller view
2. Click on an item
3. Click Close
4. The button in the top right corner will say "close" instead of "menu"

Unstarted Functionality:
- Active link updates as user scrolls 
- Active items have a 2px color teal left border

**Comment by bengolder** [comment]
It looks like this has been solved!
