### ISSUE TITLE
Move labels and extraneous button types to admin-specific file

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/honeycrisp-gem#115]
Per discussion with Norris, we want to streamline by removing some un/under-used components.

Remove these button types:
- `button--small`
- `button--large`
- `button--cta`
- `button--link`

Also rename the remaining button classes. The white button (currently `button`) should be `button--secondary`, and the teal button should be the default as `button`. (don't do this part if it's too much work)

Also remove the entire `label` component.

**Comment by hartsick** [comment]
After talking with Rachel, we decided not to rename the button classes because it involve too much coordination across teams (they'd have to update all button classes their code bases when updating this gem).

This will be a breaking change (some projects may use the button types we're planning to remove), so we should plan to bump the minor version.

**Comment by hartsick** [comment]
We discussed moving the admin-related classes to a new file, e.g. `_admin.scss`, so we can start to differentiate admin styleguide vs client styleguide.

**Comment by mrotondo** [comment]
Per conversation w/ @racheledelman:
- we are keeping `button--small`
- `button--large` has already been removed
- renaming `button` to `button-secondary` and `button-primary` to `button` is too much work
- we will make a change to get rid of `button--cta` and replace usages with `button--primary`
- we will adjust the style of button--link to visually indicate its bounds
