### ISSUE TITLE
Decide whether and how to maintain the CfAFormBuilder

### ISSUE THREAD

**Issue by hartsick** [codeforamerica/honeycrisp-gem#124]
The CfAFormBuilder is not used by any active projects, and Norris had raised some concerns about the form styling with this design update: https://github.com/codeforamerica/cfa-styleguide-gem/pull/123

Should we continue to maintain the styleguide's formbuilder? And if so, should we re-build it from [GCF's form builder](https://github.com/codeforamerica/gcf-backend/blob/master/app/helpers/gcf_form_builder.rb) or keep [what we currently have](https://github.com/codeforamerica/cfa-styleguide-gem/blob/master/app/helpers/cfa/styleguide/cfa_form_builder.rb)?

@bengolder as someone who might be using this soon, I'd love your thoughts on the question above!

**Comment by bengolder** [comment]
I think it's useful to have a formbuilder. I think there are some decisions & improvements to make to keep it useful. Assuming I have a 2nd engineer on my team, we may be able to contribute back to it. In my usage during the prototype I frequently created custom formbuilder methods because the current formbuilder didn't quite meet my needs (but it's close). In particular, I wanted to be able to create `<h1>` labels for single question pages for better screen reader hierarchy.

https://github.com/codeforamerica/eitc/blob/master/app/helpers/eitc/eitc_form_builder.rb

In terms of choosing between GCF & the current formbuilder, I would lean towards whichever feels most up-to-date with our accessibility standards & design and is most widely used. I'm guessing that would be GCF, but I'm not sure.

Since GCF has its own form builder, we could use EITC as an initial use case for a shared formbuilder, and review the work with other styleguide stakeholders, and fold it back in to assist later prototyping efforts.

**Comment by hartsick** [comment]
Notes from discussion about FormBuilder here: https://docs.google.com/document/d/1LfwFEr1VX0uTTpBQdhjSrdM_ycAsJkiAG_FLzu3PHko/edit

**Comment by hartsick** [comment]
Closed by #204
