### ISSUE TITLE
How can we add a new icon to the icon set?

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/honeycrisp-gem#154]
We'd like to add the "search" icon to our icon set
https://material.io/resources/icons/?icon=search&style=baseline

![Screen Shot 2019-12-18 at 9 56 51 AM](https://user-images.githubusercontent.com/451510/71110746-bd12ab00-217c-11ea-9add-86b2b4cc9228.png)

 The documentation says:

> These are Google Material icons. Note: this is an IcoMoon subset, rather than the full set of Material icons because we didn't want to load them all. You can add more icons to the set, but it's kind of complicated.

Is there any documentation of the process for adding another icon that we could add or link to?

**Comment by racheledelman** [comment]
Per Norris:

> The way to get icons into the set was lost long ago :(
> 
> I believe we used icomoon to generate a custom subset of the material design icon font. But i don’t think we have access to the icomoon account anymore. 
> 
> You could make a new subset font OR just maybe use default material design font. The reason we subset initially was because we were trying to be very judicious with performance but because we never really set an internal performance standard, not clear if it’s really worth the effort. 
> 
> I’ll leave it to the new powers that be to make their own decision!

Therefore I see our two options as:

A) Someone makes a new [IcoMoon](https://icomoon.io/) account, recreates our set of Material Icons, and documents the process of making changes

or

B) We use the [default Material Design icon font](https://google.github.io/material-design-icons/#icon-font-for-the-web), which is 42kb (vs 10.8kb for our custom subset)

**Comment by racheledelman** [comment]
In discussion with @lkogler, we recommend B

**Comment by SymonneSingleton** [comment]
the Material icon set is functional. However, we should add directions for users about how to add their own fonts if needed.

**Comment by anule** [comment]
@SymonneSingleton  and I made a lot of progress on this story today. We have decided to use Sass maps and mixins to generate icons instead of ligatures because of the styling flexibility of the former. 

While ligatures are the recommended implementation for the Material icon set, there is not a clear path to style individual icons in the .scss file. Since there are inconsistencies in alignment in the icon library, we felt this was not the best route to take. Additionally, ligatures are not supported by all IE browsers, which makes them less ideal for our work
