### ISSUE TITLE
Internet Explorer 11 bugs

### ISSUE THREAD

**Issue by luigi** [codeforamerica/honeycrisp-gem#213]
I did an audit of IE11 using a Microsoft Surface running Windows 10 Home. I went through both GCF and P-EBT apps. It was a pretty good experience!

Despite Microsoft announcing an end-of-life for IE11 in favor of their WebKit-based Edge browser, a small but significant percentage of our website visitors still use IE11:

* MN P-EBT: 2.1%
* GCF: 1.2%
* CA P-EBT: 1%

The bugs below mainly cause confusion. There were no showstopper bugs found.

## 1. Checkbox labels in checkbox set are not clickable

<img width="369" alt="checkbox-set-1" src="https://user-images.githubusercontent.com/417/93491806-207e6480-f8d8-11ea-8347-8fb5118cb88a.PNG">

When clicking or tapping on the label, the checkbox should get selected. Honeycrisp purposefully gives the user a large tap target. However in IE11, only clicking on the checkbox itself will select it.

## 2. Select dropdowns are mis-formatted

<img width="379" alt="select-1" src="https://user-images.githubusercontent.com/417/93492047-61767900-f8d8-11ea-995d-0b70e1fb7cfe.PNG">

IE11 inserts its own down-caret into the select field. When the dropdown is engaged with many options, IE11 inserts its own scrollbar. Those should be hidden.

<img width="270" alt="select-2" src="https://user-images.githubusercontent.com/417/93492146-7d7a1a80-f8d8-11ea-8f31-fece7db3b355.PNG">

When the select dropdown is engaged and there's a disabled `<option>` element (like "Select your county" in the screenshot), the background of that `<option>` turns grey and it's difficult to read .

**Comment by sree-cfa** [comment]
>When clicking or tapping on the label, the checkbox should get selected. Honeycrisp purposefully gives the user a large tap target. However in IE11, only clicking on the checkbox itself will select it.

This is working in "Form Elements" but not "Form Builder" because of the `<label>` tag containing the `for` attribute in one but not the other. If we just add the label tag based on id or name, it will break in other browsers since it's not unique.
Not sure this is worth the ~20 changes to labels in the repo to make a unique name/id to use the `for` tag to make this work in IE.

> When the select dropdown is engaged and there's a disabled <option> element (like "Select your county" in the screenshot), the background of that <option> turns grey and it's difficult to read .

Seems like this is something that can't be customized for IE. IE will ignored always set the background to this dark grey for disabled, selected options

**Comment by sree-cfa** [comment]
It also seems like `for` is needed for accessibility, so it's probably worth adding

**Comment by coltborg** [comment]
Because of the improvemen

**Comment by coltborg** [comment]
(Pressed a keyboard shortcut that closed the issue 🤔 🥴)

**Comment by coltborg** [comment]
Because of an improvement that added auto-prefixes for vendor styles, `appearance` for `<select>`'s in IE11 are now properly styled. Which means that the second issue has been resolved. No double arrows or disabled options being gray.

<img width="1920" alt="selects-no-longer-have-double-arrow" src="https://user-images.githubusercontent.com/9101728/134053806-c6f38e8e-ccf6-468f-b38b-20017242c5b5.png">

<img width="1185" alt="disabled-options-no-longer-gray" src="https://user-images.githubusercontent.com/9101728/134053810-14702bb3-542e-4514-8d2e-aeb012f21ba9.png">

**Comment by luigi** [comment]
:tada:

**Comment by coltborg** [comment]
I walked through the on-boarding process and all checkboxes were able to be clicked on the `label` to select it. [I think this improvement](https://github.com/codeforamerica/shiba/commit/963a5897f0020ecbc7a50c6f2a55cfde7580a8c9) that added the `for` attribute to `<label>`'s helped fix this problem.

https://user-images.githubusercontent.com/9101728/134059516-4a45b3af-4df0-469a-9835-95c95e881f44.mp4

**Comment by coltborg** [comment]
All issues brought up by this issue have been resolved by other code changes, no further action needs to be taken! 🎉
