### ISSUE TITLE
Center content for document pages

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/honeycrisp-gem#272]
For upload documents and document recommendation, card is moved over and not centered

Small style discrepancy we encountered when upgrading SHIBA to the latest version of Honeycrisp

[Percy failures](https://percy.io/e1ec91a4/shiba/builds/11776575/changed/662483492?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280)

**Comment by coltborg** [comment]
This is happening because `.grid-ignore-mobile` doesn't have `margin-left: auto; margin-right: auto;` defined anymore.

I think it has something to do with [`neat` being pulled out and placed in the `vendor` folder](https://github.com/codeforamerica/honeycrisp-gem/pull/233/files).

**Comment by coltborg** [comment]
Page was not centering correctly because .grid-ignore-mobile was used only in SHIBA and not Honeycrisp. To fix the issue we added .grid-ignore-mobile to the css file in SHIBA.
[Custom code originally in `honeycrisp.css` that we moved to `shiba.css`](https://github.com/codeforamerica/shiba/commit/397503fc755acf50bcf200a16a389d4d936fa4cb)
