### ISSUE TITLE
Home link turned green

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/honeycrisp-gem#274]
Small style discrepancy we encountered when upgrading SHIBA to the latest version of Honeycrisp

[Percy failures](https://percy.io/e1ec91a4/shiba/builds/11776575/changed/662483492?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280)

**Comment by coltborg** [comment]
This was caused by [a Honeycrisp change that introduced more custom colors and psuedoclasses for link states](https://github.com/codeforamerica/honeycrisp-gem/commit/afca6fe8c9686c66574504e6c09633a085b6b0d4)

We added additional pseudo selectors to prevent the logo from being affected by those additional default anchor tag colors.
