### ISSUE TITLE
Fix reveal component

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/honeycrisp-gem#275]
Reveal’s hard hidden on page load with `.is-hidden` class on the wrong element.

It looks like [the reveal](http://honeycrisp.herokuapp.com/cfa/styleguide#molecules-reveal) does not have a unit test and has a breaking change with 0.10.2

In the documentation, the entire reveal component is incorrectly hidden on page load, when it should only be hiding the additional details.

**Comment by coltborg** [comment]
When did the reveal disappear? - `v0.10.1`

<img width="992" alt="Screen Shot 2021-08-03 at 5 51 25 PM" src="https://user-images.githubusercontent.com/9101728/128096368-68c4940e-21c4-49f7-b8ce-d75bebe905d6.png">

**Comment by coltborg** [comment]
This issue is coming from a new CSS definitaion of `.is-hidden` for form builder to use, when reveal was using that same class name to hide a nested element. This can be resolved with changing the reveal class name.

<img width="1427" alt="Screen Shot 2021-08-03 at 5 54 57 PM" src="https://user-images.githubusercontent.com/9101728/128096690-f9dc01c4-7ee9-4172-98d6-47746f3de1da.png">

<img width="556" alt="Screen Shot 2021-08-03 at 5 55 03 PM" src="https://user-images.githubusercontent.com/9101728/128096696-9f1829a5-b161-453a-aab2-02ad65592c17.png">

**Comment by coltborg** [comment]
- [ ] Change `.reveal.is-hidden` class name to not use `.is-hidden`
- [ ] Add tests to cover reveal component
